import os

# General
DATE_TIME_PATTERN = "%H:%M:%S"


# Constants for file paths
PROMPTS_DIR = "prompts"

# Dataset
DATASET_NAME = "bitext/Bitext-customer-support-llm-chatbot-training-dataset"
DATASET_SPLIT_NAME = "train"


# LLM
LLM_MODEL_NAME = "gpt-4o-mini"  # "gpt-3.5-turbo"  # "gpt-4o-mini"
LLM_TEMPERATURE = 0.0
LLM_TOP_P = 1.0
DEFAULT_PARALLEL_TOOL_CALLS = False


# Router
ROUTER_SYSTEM_PROMPT_FILE_NAME = "router_system_prompt.txt"
ROUTER_SYSTEM_PROMPT_FILE_PATH = os.path.join(
    PROMPTS_DIR, ROUTER_SYSTEM_PROMPT_FILE_NAME
)


# Agents
MAX_ITERATIONS = 50


# Structured Query Agent
STRUCTURED_QUERY_AGENT_SYSTEM_PROMPT_FILE_NAME = (
    "structured_query_agent_system_prompt.txt"
)
STRUCTURED_QUERY_AGENT_SYSTEM_PROMPT_FILE_PATH = os.path.join(
    PROMPTS_DIR, STRUCTURED_QUERY_AGENT_SYSTEM_PROMPT_FILE_NAME
)


# Unstructured Query Agent
UNSTRUCTURED_QUERY_AGENT_SYSTEM_PROMPT_FILE_NAME = (
    "unstructured_query_agent_system_prompt.txt"
)
UNSTRUCTURED_QUERY_AGENT_SYSTEM_PROMPT_FILE_PATH = os.path.join(
    PROMPTS_DIR, UNSTRUCTURED_QUERY_AGENT_SYSTEM_PROMPT_FILE_NAME
)

SUMMARIZE_BATCH_PROMPT_FILE_NAME = "summarize_batch_prompt.txt"
SUMMARIZE_BATCH_PROMPT_FILE_PATH = os.path.join(
    PROMPTS_DIR, SUMMARIZE_BATCH_PROMPT_FILE_NAME
)

SUMMARIZE_ALL_BATCHES_PROMPT_FILE_NAME = "summarize_all_batches_prompt.txt"
SUMMARIZE_ALL_BATCHES_PROMPT_FILE_PATH = os.path.join(
    PROMPTS_DIR, SUMMARIZE_ALL_BATCHES_PROMPT_FILE_NAME
)

SUMMARIZE_DEFAULT_BATCH_SIZE = 20
SUMMARIZE_DEFAULT_N_BATCHES = 5


# Out of Scope Handler
OUT_OF_SCOPE_HANDLER_SYSTEM_PROMPT_FILE_NAME = "out_of_scope_node_system_prompt.txt"
OUT_OF_SCOPE_HANDLER_SYSTEM_PROMPT_FILE_PATH = os.path.join(
    PROMPTS_DIR, OUT_OF_SCOPE_HANDLER_SYSTEM_PROMPT_FILE_NAME
)
